[SIMULATION_PERIOD]
time_start = "2019-01-01T00:00"
time_end = "2020-01-01T00:00"

[FILENAMES]
data_path = "./data/"
input_netcdf = "ERA5/ERA5_2019.nc"
output_prefix = "ERA5_2019"

[RESTART]
restart = false

[STAKE_DATA]
stake_evaluation = false
stakes_loc_file = "./data/input/HEF/loc_stakes.csv"
stakes_data_file = "./data/input/HEF/data_stakes_hef.csv"
eval_method = "rmse"
obs_type = "snowheight"

[DIMENSIONS]
WRF = false
WRF_X_CSPY = false
northing = "lat"
easting = "lon"

[COMPRESSION]
compression_level = 2

[PARALLELIZATION]
slurm_use = false
workers = 4
local_port = 8786

[FULL_FIELDS]
full_field = false

[FORCINGS]
force_use_TP = true
force_use_N = false

[SUBSET]
tile = false
xstart = 20
xend = 40
ystart = 20
yend = 40

[OUTPUT_VARIABLES]
output_atm = "T2,RH2,U2,RAIN,SNOWFALL,RRR,PRES,N,G,LWin,LWout,H,LE,B,QRR,Z0,ALBEDO,TS"
output_internal = "ME,MB,surfMB,intMB,EVAPORATION,SUBLIMATION,CONDENSATION,DEPOSITION,surfM,subM,Q,REFREEZE,SNOWHEIGHT,TOTALHEIGHT,LAYERS"
output_full = "HEIGHT,RHO,T,LWC,CC,POROSITY,LW,ICE_FRACTION,IRREDUCIBLE_WATER,REFREEZE"
